import { z } from 'zod';
import { HoldersStatsSchema } from './EnrichedHoldersData.ts';
import { TokenTypeSchema } from './EnrichedMarketData.ts';
import { SecurityFlagsSchema } from './SecuritySchemas.ts';

export const TokenDetailsOutput = z
  .object({
    address: z.string(),
    chainId: z.string(),
    symbol: z.string().nullable(),
    name: z.string().nullable(),
    decimals: z.coerce.number().default(0),
    id: z.number().nullable().optional().default(null),

    priceUSD: z.coerce.number().default(0),
    priceToken: z.coerce.number().default(0),
    priceTokenString: z.string(),
    approximateReserveUSD: z.coerce.number().default(0),
    approximateReserveTokenRaw: z.string(),
    approximateReserveToken: z.coerce.number().default(0),
    totalSupply: z.coerce.number().default(0),
    circulatingSupply: z.coerce.number().default(0),
    marketCapUSD: z.coerce.number().default(0),
    marketCapDilutedUSD: z.coerce.number().optional().default(0),
    logo: z.string().nullable(),
    originLogoUrl: z.string().nullable().optional(),
    rank: z.coerce.number().nullable().default(null),
    cexs: z.array(z.string()).default([]),

    exchange: z
      .object({
        name: z.string(),
        logo: z.string(),
      })
      .optional(),

    factory: z.string().nullable().optional(),
    source: z.string().nullable().optional(),
    sourceFactory: z.string().nullable().optional(),
    sourceMetadata: z
      .object({
        name: z.string(),
        logo: z.string(),
      })
      .nullable()
      .optional(),

    liquidityUSD: z.coerce.number().optional(),
    liquidityMaxUSD: z.coerce.number().optional(),
    bonded: z.boolean().optional(),
    bondingPercentage: z.coerce.number().optional(),
    bondingCurveAddress: z.string().nullable().optional(),
    preBondingFactory: z.string().optional(),
    poolAddress: z.string().optional(),

    blockchain: z.string().optional(),
    type: z.string().optional(),
    tokenType: TokenTypeSchema,

    deployer: z.string().nullable().optional(),
    bondedAt: z.coerce.date().nullable(),
    athUSD: z.coerce.number().optional(),
    atlUSD: z.coerce.number().optional(),
    athDate: z.coerce.date().optional(),
    atlDate: z.coerce.date().optional(),

    priceChange1minPercentage: z.coerce.number().default(0),
    priceChange5minPercentage: z.coerce.number().default(0),
    priceChange1hPercentage: z.coerce.number().default(0),
    priceChange4hPercentage: z.coerce.number().default(0),
    priceChange6hPercentage: z.coerce.number().default(0),
    priceChange12hPercentage: z.coerce.number().default(0),
    priceChange24hPercentage: z.coerce.number().default(0),

    volume1minUSD: z.coerce.number().default(0),
    volume5minUSD: z.coerce.number().default(0),
    volume15minUSD: z.coerce.number().default(0),
    volume1hUSD: z.coerce.number().default(0),
    volume4hUSD: z.coerce.number().default(0),
    volume6hUSD: z.coerce.number().default(0),
    volume12hUSD: z.coerce.number().default(0),
    volume24hUSD: z.coerce.number().default(0),

    volumeBuy1minUSD: z.coerce.number().default(0),
    volumeBuy5minUSD: z.coerce.number().default(0),
    volumeBuy15minUSD: z.coerce.number().default(0),
    volumeBuy1hUSD: z.coerce.number().default(0),
    volumeBuy4hUSD: z.coerce.number().default(0),
    volumeBuy6hUSD: z.coerce.number().default(0),
    volumeBuy12hUSD: z.coerce.number().default(0),
    volumeBuy24hUSD: z.coerce.number().default(0),

    volumeSell1minUSD: z.coerce.number().default(0),
    volumeSell5minUSD: z.coerce.number().default(0),
    volumeSell15minUSD: z.coerce.number().default(0),
    volumeSell1hUSD: z.coerce.number().default(0),
    volumeSell4hUSD: z.coerce.number().default(0),
    volumeSell6hUSD: z.coerce.number().default(0),
    volumeSell12hUSD: z.coerce.number().default(0),
    volumeSell24hUSD: z.coerce.number().default(0),

    trades1min: z.coerce.number().default(0),
    trades5min: z.coerce.number().default(0),
    trades15min: z.coerce.number().default(0),
    trades1h: z.coerce.number().default(0),
    trades4h: z.coerce.number().default(0),
    trades6h: z.coerce.number().default(0),
    trades12h: z.coerce.number().default(0),
    trades24h: z.coerce.number().default(0),

    buys1min: z.coerce.number().default(0),
    buys5min: z.coerce.number().default(0),
    buys15min: z.coerce.number().default(0),
    buys1h: z.coerce.number().default(0),
    buys4h: z.coerce.number().default(0),
    buys6h: z.coerce.number().default(0),
    buys12h: z.coerce.number().default(0),
    buys24h: z.coerce.number().default(0),

    sells1min: z.coerce.number().default(0),
    sells5min: z.coerce.number().default(0),
    sells15min: z.coerce.number().default(0),
    sells1h: z.coerce.number().default(0),
    sells4h: z.coerce.number().default(0),
    sells6h: z.coerce.number().default(0),
    sells12h: z.coerce.number().default(0),
    sells24h: z.coerce.number().default(0),

    buyers1min: z.coerce.number().default(0),
    buyers5min: z.coerce.number().default(0),
    buyers15min: z.coerce.number().default(0),
    buyers1h: z.coerce.number().default(0),
    buyers4h: z.coerce.number().default(0),
    buyers6h: z.coerce.number().default(0),
    buyers12h: z.coerce.number().default(0),
    buyers24h: z.coerce.number().default(0),

    sellers1min: z.coerce.number().default(0),
    sellers5min: z.coerce.number().default(0),
    sellers15min: z.coerce.number().default(0),
    sellers1h: z.coerce.number().default(0),
    sellers4h: z.coerce.number().default(0),
    sellers6h: z.coerce.number().default(0),
    sellers12h: z.coerce.number().default(0),
    sellers24h: z.coerce.number().default(0),

    traders1min: z.coerce.number().default(0),
    traders5min: z.coerce.number().default(0),
    traders15min: z.coerce.number().default(0),
    traders1h: z.coerce.number().default(0),
    traders4h: z.coerce.number().default(0),
    traders6h: z.coerce.number().default(0),
    traders12h: z.coerce.number().default(0),
    traders24h: z.coerce.number().default(0),

    feesPaid1minUSD: z.coerce.number().default(0),
    feesPaid5minUSD: z.coerce.number().default(0),
    feesPaid15minUSD: z.coerce.number().default(0),
    feesPaid1hUSD: z.coerce.number().default(0),
    feesPaid4hUSD: z.coerce.number().default(0),
    feesPaid6hUSD: z.coerce.number().default(0),
    feesPaid12hUSD: z.coerce.number().default(0),
    feesPaid24hUSD: z.coerce.number().default(0),
    totalFeesPaidUSD: z.coerce.number().default(0),
    totalFeesPaidNativeRaw: z.coerce.string().default('0'),

    organicTrades1min: z.coerce.number().default(0),
    organicTrades5min: z.coerce.number().default(0),
    organicTrades15min: z.coerce.number().default(0),
    organicTrades1h: z.coerce.number().default(0),
    organicTrades4h: z.coerce.number().default(0),
    organicTrades6h: z.coerce.number().default(0),
    organicTrades12h: z.coerce.number().default(0),
    organicTrades24h: z.coerce.number().default(0),

    organicTraders1min: z.coerce.number().default(0),
    organicTraders5min: z.coerce.number().default(0),
    organicTraders15min: z.coerce.number().default(0),
    organicTraders1h: z.coerce.number().default(0),
    organicTraders4h: z.coerce.number().default(0),
    organicTraders6h: z.coerce.number().default(0),
    organicTraders12h: z.coerce.number().default(0),
    organicTraders24h: z.coerce.number().default(0),

    organicVolume1minUSD: z.coerce.number().default(0),
    organicVolume5minUSD: z.coerce.number().default(0),
    organicVolume15minUSD: z.coerce.number().default(0),
    organicVolume1hUSD: z.coerce.number().default(0),
    organicVolume4hUSD: z.coerce.number().default(0),
    organicVolume6hUSD: z.coerce.number().default(0),
    organicVolume12hUSD: z.coerce.number().default(0),
    organicVolume24hUSD: z.coerce.number().default(0),

    organicVolumeBuy1minUSD: z.coerce.number().default(0),
    organicVolumeBuy5minUSD: z.coerce.number().default(0),
    organicVolumeBuy15minUSD: z.coerce.number().default(0),
    organicVolumeBuy1hUSD: z.coerce.number().default(0),
    organicVolumeBuy4hUSD: z.coerce.number().default(0),
    organicVolumeBuy6hUSD: z.coerce.number().default(0),
    organicVolumeBuy12hUSD: z.coerce.number().default(0),
    organicVolumeBuy24hUSD: z.coerce.number().default(0),

    organicVolumeSell1minUSD: z.coerce.number().default(0),
    organicVolumeSell5minUSD: z.coerce.number().default(0),
    organicVolumeSell15minUSD: z.coerce.number().default(0),
    organicVolumeSell1hUSD: z.coerce.number().default(0),
    organicVolumeSell4hUSD: z.coerce.number().default(0),
    organicVolumeSell6hUSD: z.coerce.number().default(0),
    organicVolumeSell12hUSD: z.coerce.number().default(0),
    organicVolumeSell24hUSD: z.coerce.number().default(0),

    organicBuys1min: z.coerce.number().default(0),
    organicBuys5min: z.coerce.number().default(0),
    organicBuys15min: z.coerce.number().default(0),
    organicBuys1h: z.coerce.number().default(0),
    organicBuys4h: z.coerce.number().default(0),
    organicBuys6h: z.coerce.number().default(0),
    organicBuys12h: z.coerce.number().default(0),
    organicBuys24h: z.coerce.number().default(0),

    organicSells1min: z.coerce.number().default(0),
    organicSells5min: z.coerce.number().default(0),
    organicSells15min: z.coerce.number().default(0),
    organicSells1h: z.coerce.number().default(0),
    organicSells4h: z.coerce.number().default(0),
    organicSells6h: z.coerce.number().default(0),
    organicSells12h: z.coerce.number().default(0),
    organicSells24h: z.coerce.number().default(0),

    organicBuyers1min: z.coerce.number().default(0),
    organicBuyers5min: z.coerce.number().default(0),
    organicBuyers15min: z.coerce.number().default(0),
    organicBuyers1h: z.coerce.number().default(0),
    organicBuyers4h: z.coerce.number().default(0),
    organicBuyers6h: z.coerce.number().default(0),
    organicBuyers12h: z.coerce.number().default(0),
    organicBuyers24h: z.coerce.number().default(0),

    organicSellers1min: z.coerce.number().default(0),
    organicSellers5min: z.coerce.number().default(0),
    organicSellers15min: z.coerce.number().default(0),
    organicSellers1h: z.coerce.number().default(0),
    organicSellers4h: z.coerce.number().default(0),
    organicSellers6h: z.coerce.number().default(0),
    organicSellers12h: z.coerce.number().default(0),
    organicSellers24h: z.coerce.number().default(0),

    createdAt: z.coerce.date().nullable(),
    latestTradeDate: z.coerce.date().nullable(),

    holdersCount: z.coerce.number().default(0),

    description: z.string().nullable(),
    socials: z.object({
      twitter: z.string().nullable(),
      website: z.string().nullable(),
      telegram: z.string().nullable(),
      others: z.record(z.unknown()).nullable(),
      uri: z.string().optional(),
    }),

    security: SecurityFlagsSchema.nullable(),

    twitterReusesCount: z.coerce.number().nullable().default(0),
    twitterRenameCount: z.coerce.number().default(0),
    twitterRenameHistory: z
      .array(
        z.object({
          username: z.string(),
          lastChecked: z.string(),
        }),
      )
      .default([]),

    deployerMigrationsCount: z.coerce.number().default(0),
    deployerTokensCount: z.coerce.number().default(0),
    dexscreenerListed: z.boolean().nullable().default(false),
    dexscreenerHeader: z.string().nullable().default(null),
    dexscreenerAdPaid: z.boolean().nullable().default(false),
    dexscreenerAdPaidDate: z.coerce.date().nullable().default(null),
    dexscreenerSocialPaid: z.boolean().nullable().default(false),
    dexscreenerSocialPaidDate: z.coerce.date().nullable().default(null),

    liveStatus: z.string().nullable(),
    liveThumbnail: z.string().nullable(),
    livestreamTitle: z.string().nullable(),
    liveReplyCount: z.number().nullable(),
    dexscreenerBoosted: z.boolean().nullable().default(false),
    dexscreenerBoostedDate: z.coerce.date().nullable().default(null),
    dexscreenerBoostedAmount: z.number().nullable().default(0),

    // Trending score fields
    trendingScore1min: z.coerce.number().default(0),
    trendingScore5min: z.coerce.number().default(0),
    trendingScore15min: z.coerce.number().default(0),
    trendingScore1h: z.coerce.number().default(0),
    trendingScore4h: z.coerce.number().default(0),
    trendingScore6h: z.coerce.number().default(0),
    trendingScore12h: z.coerce.number().default(0),
    trendingScore24h: z.coerce.number().default(0),

    isMayhemMode: z.boolean().nullable().default(null),
    isCashbackCoin: z.boolean().nullable().default(null),
    isAgentMode: z.boolean().nullable().default(null),
  })
  .merge(HoldersStatsSchema);

export type TokenDetailsOutputType = z.infer<typeof TokenDetailsOutput>;
